# Generated by Django 5.1.3 on 2024-12-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("desc", models.TextField()),
                ("address", models.CharField()),
                ("pType", models.CharField()),
                ("price", models.FloatField()),
                ("payment", models.CharField()),
                ("bedrooms", models.SmallIntegerField()),
                ("bathrooms", models.SmallIntegerField()),
                ("sizeW", models.SmallIntegerField()),
                ("sizeB", models.SmallIntegerField()),
                ("available", models.BooleanField(default=False)),
            ],
        ),
    ]
