# Generated by Django 5.1.3 on 2024-12-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="pType",
        ),
        migrations.RemoveField(
            model_name="property",
            name="payment",
        ),
        migrations.AddField(
            model_name="property",
            name="paymentType",
            field=models.CharField(
                choices=[("b", "buy"), ("r", "rent")], default=None, max_length=1
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="propertyType",
            field=models.CharField(
                choices=[("d", "duplex"), ("a", "apartment"), ("l", "land")],
                default=None,
                max_length=1,
            ),
        ),
    ]
