# Generated by Django 5.1.3 on 2024-12-01 17:19

import address.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("properties", "0002_remove_property_ptype_remove_property_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="address",
            field=address.models.AddressField(
                on_delete=django.db.models.deletion.CASCADE, to="address.address"
            ),
        ),
    ]
