# Generated by Django 5.1.3 on 2024-12-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_alter_property_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(max_length=500),
        ),
    ]
